// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU7wpjCt2rNRobN70Sy1QgbLgPdALpgUE',
    appId: '1:168370628046:web:5c369fcc194ede0f35f79f',
    messagingSenderId: '168370628046',
    projectId: 'autilog-e5499',
    authDomain: 'autilog-e5499.firebaseapp.com',
    storageBucket: 'autilog-e5499.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByG9seZ08GoLN2HLb59aZMiHGhADOCCKg',
    appId: '1:168370628046:android:9d2e6443a2db789535f79f',
    messagingSenderId: '168370628046',
    projectId: 'autilog-e5499',
    storageBucket: 'autilog-e5499.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAncSOlPrX3DiJCjKG1Rh_Xh5mJrvL14lM',
    appId: '1:168370628046:ios:c47abb32365e631135f79f',
    messagingSenderId: '168370628046',
    projectId: 'autilog-e5499',
    storageBucket: 'autilog-e5499.firebasestorage.app',
    iosBundleId: 'com.example.autilog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAncSOlPrX3DiJCjKG1Rh_Xh5mJrvL14lM',
    appId: '1:168370628046:ios:c47abb32365e631135f79f',
    messagingSenderId: '168370628046',
    projectId: 'autilog-e5499',
    storageBucket: 'autilog-e5499.firebasestorage.app',
    iosBundleId: 'com.example.autilog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU7wpjCt2rNRobN70Sy1QgbLgPdALpgUE',
    appId: '1:168370628046:web:5656b303966f4e4635f79f',
    messagingSenderId: '168370628046',
    projectId: 'autilog-e5499',
    authDomain: 'autilog-e5499.firebaseapp.com',
    storageBucket: 'autilog-e5499.firebasestorage.app',
  );
}
